### PR TITLE
parse all matched flags firstly, mismatched flag as args (#35)

### PR DESCRIPTION
**Pull request by sejust**

### CODE REVIEW

**Comment by skaldesh** [comment]
This breaks the current behavior. Flags have always been reported as invalid if you passed the wrong one to a command. Your code simply ignores this now.

**Comment by skaldesh** [comment]
We like the `cmd --flag -- -arg` approach more, if you want to submit a PR, please implement it this way

**Comment by sejust** [comment]
> We like the `cmd --flag -- -arg` approach more, if you want to submit a PR, please implement it this way

Thanks, I got it. So in the current design paradigm, i cannot pass the arg starts with char '-' even if this considered flag is not defined.

**Comment by sejust** [comment]
r

**Pull request closed without merging**
